# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff6f6d31fae684d912ebed90c00d2c334ae6278154535f63b32e77eb7570b1154b76254b51b81a9f0e427d34a0f325aff2bc3c780b349317d0dc79d8c95dae35

test:
  secret_key_base: 88a8bd9e9d336a0b68bd0a377460310d01f9ef9929a53a4aa8e9f39e8050721a4c933a6ad50afdee45d908a949c2cb95a96a3d77630acf83cb884dd697562c45

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
